-- FirstVue: MISSING pieces detected against live project sdssshegqdwobjelxzkp
-- Generated by cloud agent schema scan (2026-08-15).
-- Paste into Supabase SQL Editor and Run. Safe to re-run.
--
-- Verified already present (do NOT need re-paste for these):
--   - Demo seed auth users fvdemo01..25 + profiles (visible via profile_public_cards)
--   - Messaging fv_msg_* tables from 20260915
--   - Feed RPCs (fetch_ranked_main_feed, etc.), delete_my_account, set_post_reaction
--   - profile_media.caption, profile_public_cards, business_media.featured_for_trending
--   - Storage buckets profile-media / business-media / professional-media / rental-media
--
-- Confirmed MISSING on live:
--   1) list_profile_followers / list_profile_following RPCs
--   2) professional_media columns: media_type, featured_for_trending, caption, thumbnail_path
--   3) Authenticated profiles summary SELECT policy (needed for follower lists / directory)

-- ---------------------------------------------------------------------------
-- 1) Profile follow list RPCs + summary read policy
--    Source: supabase/migrations/20260824_profile_follow_list_rpcs.sql
-- ---------------------------------------------------------------------------

drop policy if exists "Authenticated read member profile summaries" on public.profiles;
create policy "Authenticated read member profile summaries"
  on public.profiles for select to authenticated
  using (display_name is not null or id = auth.uid());

create or replace function public.list_profile_followers(
  p_profile_id uuid,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id uuid,
  display_name text,
  username citext
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.display_name, p.username
  from public.profile_follows pf
  join public.profiles p on p.id = pf.follower_id
  where pf.following_id = p_profile_id
  order by pf.created_at desc
  limit greatest(coalesce(p_limit, 50), 1)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.list_profile_following(
  p_profile_id uuid,
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id uuid,
  display_name text,
  username citext
)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.display_name, p.username
  from public.profile_follows pf
  join public.profiles p on p.id = pf.following_id
  where pf.follower_id = p_profile_id
  order by pf.created_at desc
  limit greatest(coalesce(p_limit, 50), 1)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

revoke all on function public.list_profile_followers(uuid, integer, integer) from public;
revoke all on function public.list_profile_following(uuid, integer, integer) from public;
grant execute on function public.list_profile_followers(uuid, integer, integer) to authenticated;
grant execute on function public.list_profile_following(uuid, integer, integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 2) professional_media columns used by portfolio / trending / demo seed
--    Sources: 20260818_profile_media_trending_featured.sql + APPLY_DEMO_SEED.sql
-- ---------------------------------------------------------------------------

alter table public.professional_media
  add column if not exists storage_provider text not null default 'supabase';

alter table public.professional_media
  drop constraint if exists professional_media_storage_provider_check;
alter table public.professional_media
  add constraint professional_media_storage_provider_check
  check (storage_provider in ('supabase', 's3', 'external'));

alter table public.professional_media
  add column if not exists media_type text not null default 'image';

alter table public.professional_media
  drop constraint if exists professional_media_media_type_check;
alter table public.professional_media
  add constraint professional_media_media_type_check
  check (media_type in ('image', 'video'));

alter table public.professional_media
  add column if not exists featured_for_trending boolean not null default false;

alter table public.professional_media
  add column if not exists caption text;

alter table public.professional_media
  add column if not exists thumbnail_path text;

create index if not exists professional_media_featured_trending_idx
  on public.professional_media (professional_profile_id, featured_for_trending)
  where featured_for_trending = true;

-- ---------------------------------------------------------------------------
-- 3) Verify (run after apply; expect rows / true)
-- ---------------------------------------------------------------------------

select
  to_regprocedure('public.list_profile_followers(uuid,integer,integer)') is not null
    as has_list_followers,
  to_regprocedure('public.list_profile_following(uuid,integer,integer)') is not null
    as has_list_following;

select column_name
from information_schema.columns
where table_schema = 'public'
  and table_name = 'professional_media'
  and column_name in (
    'media_type',
    'featured_for_trending',
    'caption',
    'thumbnail_path',
    'storage_provider'
  )
order by column_name;
